"""
OmniDiag — Pydantic Schemas
============================
Dynamic Pydantic model generation for disease-specific patient input schemas.
Each disease can define its own input fields, validation rules, and example data.

Currently supports:
    - Heart Disease (CAD): 12 clinical features → 16 total after auto-engineering.
      Auto-computed features: RPP (RestingBP × MaxHR), Exercise_Risk_Index (Oldpeak × Angina),
      Age_BP_Interaction, HR_Age_Ratio, Chol_Age_Ratio.
    
    Future diseases will add their own schema definitions here.
"""

from typing import Dict, Type, List, Optional, Literal
from fastapi import HTTPException
from pydantic import BaseModel, ConfigDict, Field


# =============================================================================
# Heart Disease Schema
# =============================================================================

class HeartDiseaseInput(BaseModel):
    """
    Patient input schema for Coronary Artery Disease (CAD) risk assessment.
    
    All fields correspond to the 12 harmonized clinical features from the
    UCI Cleveland + Z-Alizadeh Sani merged dataset.
    
    **Auto-computed features (no input needed):**
    When a prediction is made, the system automatically computes:
        - RPP (Rate-Pressure Product): RestingBP × MaxHR
        - Exercise_Risk_Index: Oldpeak × ExerciseAngina (encoded)
        - Age_BP_Interaction: Age × RestingBP
        - HR_Age_Ratio: MaxHR / Age
        - Chol_Age_Ratio: Cholesterol / Age
    
    These are calculated server-side; you only need to provide the 12 base fields.
    
    Categorical fields (Sex, ChestPainType, RestingECG, ExerciseAngina,
    ST_Slope) accept both raw strings (e.g., 'M', 'ATA', 'Normal') and
    pre-encoded integers. The ModelLoader applies label encoding internally.
    """
    Age: int = Field(..., description="Age in years", ge=20, le=100)
    Sex: Literal['M', 'F'] = Field(..., description="Sex: 'M' or 'F' (or encoded 0/1)")
    ChestPainType: Literal['TA', 'ATA', 'NAP', 'ASY'] = Field(..., description="Chest pain type: 'TA', 'ATA', 'NAP', or 'ASY' (or encoded 0-3)")
    RestingBP: int = Field(..., description="Resting blood pressure (mm Hg)", ge=80, le=220)
    Cholesterol: int = Field(..., description="Serum cholesterol (mg/dl)", ge=100, le=600)
    FastingBS: int = Field(..., description="Fasting blood sugar > 120 mg/dl (1=True, 0=False)", ge=0, le=1)
    RestingECG: Literal['Normal', 'ST', 'LVH'] = Field(..., description="Resting ECG: 'Normal', 'ST', or 'LVH' (or encoded 0-2)")
    MaxHR: int = Field(..., description="Maximum heart rate achieved", ge=60, le=220)
    ExerciseAngina: Literal['Y', 'N'] = Field(..., description="Exercise-induced angina: 'Y' or 'N' (or encoded 0/1)")
    Oldpeak: float = Field(..., description="ST depression induced by exercise relative to rest")
    ST_Slope: Literal['Up', 'Flat', 'Down'] = Field(..., description="ST slope: 'Up', 'Flat', or 'Down' (or encoded 0-2)")

    model_config = ConfigDict(json_schema_extra={
        "example": {
            "Age": 54,
            "Sex": "M",
            "ChestPainType": "ATA",
            "RestingBP": 140,
            "Cholesterol": 289,
            "FastingBS": 0,
            "RestingECG": "Normal",
            "MaxHR": 122,
            "ExerciseAngina": "N",
            "Oldpeak": 0.0,
            "ST_Slope": "Flat",
        }
    })


# =============================================================================
# SHAP Explanation Response Models
# =============================================================================

class FeatureImpact(BaseModel):
    """
    A single feature's SHAP value contribution.
    
    Attributes:
        feature: The name of the feature (e.g., "Age", "ST_Slope").
        shap_value: The SHAP value for this feature. Positive values indicate
                    increased risk; negative values indicate decreased risk.
    """
    feature: str = Field(..., description="Feature name")
    shap_value: float = Field(..., description="SHAP value (positive = increased risk, negative = decreased risk)")


class Counterfactual(BaseModel):
    """
    A single 'what-if' scenario showing actionable changes to reduce risk.
    
    Generated by the DiCE-inspired CounterfactualGenerator. Each counterfactual
    proposes a set of feature changes that would flip a Positive prediction to
    Negative (high risk → low risk).
    
    Attributes:
        scenario: Human-readable description of the proposed changes.
        changes: Dict of feature_name → new_value for changed features only.
        new_probability: Predicted probability of positive class after changes.
        risk_reduction: Percentage reduction text (e.g., "44%").
        feasibility: Clinical feasibility level:
                     - "high": Lifestyle changes only (BMI, diet, exercise)
                     - "medium": Requires medical intervention (medication)
                     - "low": Multiple medical changes or unrealistic BMI drop
    """
    scenario: str = Field(
        ...,
        description="Human-readable description of the proposed changes"
    )
    changes: Dict[str, float] = Field(
        ...,
        description="Modified feature values (only changed features)"
    )
    new_probability: float = Field(
        ...,
        description="Predicted probability of positive class after changes",
        ge=0.0,
        le=1.0
    )
    risk_reduction: str = Field(
        ...,
        description="Percentage reduction in risk (e.g., '44%')"
    )
    feasibility: Literal["high", "medium", "low"] = Field(
        ...,
        description="Clinical feasibility: high=lifestyle, medium=medical, low=unrealistic"
    )


class ExplainResponse(BaseModel):
    """
    Response model for the SHAP explanation endpoint.
    
    Attributes:
        chart_data: List of feature impacts sorted by absolute SHAP value
                    descending, ready for direct consumption by the React
                    ShapBarChart component.
        text_explanation: Human-readable summary of the top 3 most impactful
                          features with direction labels.
        base_value: The base (expected) value from the SHAP explainer, useful
                    for advanced charting.
        ensemble_variance: Standard deviation across base model probabilities
                           (0 = perfect agreement, higher = more disagreement).
        model_agreement: Qualitative label for ensemble agreement.
        counterfactuals: List of diverse counterfactual scenarios showing
                         actionable changes to reduce risk (DiCE-inspired).
    """
    chart_data: List[FeatureImpact] = Field(
        ...,
        description="Sorted list of feature SHAP impacts for chart rendering"
    )
    text_explanation: str = Field(
        ...,
        description="Human-readable summary of top 3 impactful features"
    )
    base_value: float = Field(
        ...,
        description="Base (expected) value from the SHAP explainer"
    )
    ensemble_variance: Optional[float] = Field(
        None,
        description="Standard deviation of base model probabilities (model disagreement)",
        ge=0.0
    )
    model_agreement: Optional[str] = Field(
        None,
        description="Qualitative model agreement: 'high', 'moderate', or 'low'"
    )
    counterfactuals: Optional[List[Counterfactual]] = Field(
        None,
        description="Diverse counterfactual scenarios for clinical actionability"
    )


# =============================================================================
# Diabetes Schema
# =============================================================================

class DiabetesInput(BaseModel):
    """
    Patient input schema for Diabetes Risk Assessment.

    All 21 fields correspond to the CDC BRFSS 2015 Health Indicators dataset.
    Binary fields (0/1) and continuous/ordinal fields are validated with
    appropriate ranges.

    **Auto-computed features (no input needed):**
    When a prediction is made, the system automatically computes:
        - BMI_Age_Interaction, Health_Index, Lifestyle_Score, SES_Composite
        - Diabetes_Clinical_Risk

    These are calculated server-side; you only need to provide the 21 base fields.
    """
    # Binary (0/1) risk factors
    HighBP: int = Field(..., description="High blood pressure (1=Yes, 0=No)", ge=0, le=1)
    HighChol: int = Field(..., description="High cholesterol (1=Yes, 0=No)", ge=0, le=1)
    CholCheck: int = Field(..., description="Cholesterol check in past 5 years (1=Yes, 0=No)", ge=0, le=1)
    Smoker: int = Field(..., description="Smoked at least 100 cigarettes in life (1=Yes, 0=No)", ge=0, le=1)
    Stroke: int = Field(..., description="Ever told you had a stroke (1=Yes, 0=No)", ge=0, le=1)
    HeartDiseaseorAttack: int = Field(..., description="Coronary heart disease or MI (1=Yes, 0=No)", ge=0, le=1)
    PhysActivity: int = Field(..., description="Physical activity in past 30 days (1=Yes, 0=No)", ge=0, le=1)
    Fruits: int = Field(..., description="Consume fruit 1+ times per day (1=Yes, 0=No)", ge=0, le=1)
    Veggies: int = Field(..., description="Consume vegetables 1+ times per day (1=Yes, 0=No)", ge=0, le=1)
    HvyAlcoholConsump: int = Field(..., description="Heavy drinkers: adult men >14, women >7 per week (1=Yes, 0=No)", ge=0, le=1)
    AnyHealthcare: int = Field(..., description="Have any form of health insurance (1=Yes, 0=No)", ge=0, le=1)
    NoDocbcCost: int = Field(..., description="Could not see doctor due to cost (1=Yes, 0=No)", ge=0, le=1)
    DiffWalk: int = Field(..., description="Serious difficulty walking/climbing stairs (1=Yes, 0=No)", ge=0, le=1)
    Sex: int = Field(..., description="Sex: 1=Male, 0=Female", ge=0, le=1)

    # Continuous / ordinal health indicators
    BMI: float = Field(..., description="Body Mass Index", ge=10.0, le=100.0)
    MentHlth: int = Field(..., description="Days of poor mental health in past 30", ge=0, le=30)
    PhysHlth: int = Field(..., description="Days of poor physical health in past 30", ge=0, le=30)
    GenHlth: int = Field(..., description="General health: 1=Excellent, 2=Very Good, 3=Good, 4=Fair, 5=Poor", ge=1, le=5)
    Age: int = Field(..., description="Age category: 1=18-24 ... 13=80+ (BRFSS coding)", ge=1, le=13)
    Education: int = Field(..., description="Education level: 1=None to 6=College graduate", ge=1, le=6)
    Income: int = Field(..., description="Income scale: 1=<$10K to 8=>$75K", ge=1, le=8)

    model_config = ConfigDict(json_schema_extra={
        "example": {
            "HighBP": 1,
            "HighChol": 1,
            "CholCheck": 1,
            "BMI": 30.0,
            "Smoker": 1,
            "Stroke": 0,
            "HeartDiseaseorAttack": 0,
            "PhysActivity": 0,
            "Fruits": 0,
            "Veggies": 0,
            "HvyAlcoholConsump": 0,
            "AnyHealthcare": 1,
            "NoDocbcCost": 0,
            "GenHlth": 3,
            "MentHlth": 10,
            "PhysHlth": 5,
            "DiffWalk": 0,
            "Sex": 1,
            "Age": 7,
            "Education": 4,
            "Income": 4,
        }
    })


# =============================================================================
# Stroke Schema
# =============================================================================

class StrokeInput(BaseModel):
    """
    Patient input schema for Stroke Risk Assessment.

    Based on the Kaggle Stroke Prediction Dataset (11 clinical features).

    **Auto-computed features (no input needed):**
        - Age_Glucose_Interaction, BMI_Age_Risk, Vascular_Burden
        - Stroke_Clinical_Risk
    """
    gender: Literal["Male", "Female", "Other"] = Field(..., description="Patient gender")
    age: float = Field(..., description="Patient age in years", ge=0, le=120)
    hypertension: int = Field(..., description="Hypertension: 1=Yes, 0=No", ge=0, le=1)
    heart_disease: int = Field(..., description="Heart disease history: 1=Yes, 0=No", ge=0, le=1)
    ever_married: Literal["Yes", "No"] = Field(..., description="Marital status")
    work_type: Literal["Private", "Self-employed", "Govt_job", "children", "Never_worked"] = Field(
        ..., description="Employment type"
    )
    Residence_type: Literal["Urban", "Rural"] = Field(..., description="Residence type")
    avg_glucose_level: float = Field(..., description="Average blood glucose level (mg/dL)", ge=50, le=300)
    bmi: float = Field(..., description="Body mass index", ge=10, le=70)
    smoking_status: Literal["formerly smoked", "never smoked", "smokes", "Unknown"] = Field(
        ..., description="Smoking status"
    )

    model_config = ConfigDict(json_schema_extra={
        "example": {
            "gender": "Male",
            "age": 67,
            "hypertension": 0,
            "heart_disease": 1,
            "ever_married": "Yes",
            "work_type": "Private",
            "Residence_type": "Urban",
            "avg_glucose_level": 228.69,
            "bmi": 36.6,
            "smoking_status": "formerly smoked",
        }
    })


# =============================================================================
# CKD Schema
# =============================================================================

class CKDInput(BaseModel):
    """
    Patient input schema for Chronic Kidney Disease classification.

    Based on the UCI CKD Dataset (24 clinical + lab features).

    **Auto-computed features (no input needed):**
        - BUN_Creatinine_Ratio, Anemia_Index, Electrolyte_Balance,
          Protein_Sugar_Load, CKD_Clinical_Risk
    """
    age: float = Field(..., description="Patient age in years", ge=0, le=120)
    bp: float = Field(..., description="Blood pressure (mm/Hg)", ge=50, le=200)
    sg: float = Field(..., description="Specific gravity of urine", ge=1.005, le=1.025)
    al: float = Field(..., description="Albumin in urine (0–5 scale)", ge=0, le=5)
    su: float = Field(..., description="Sugar in urine (0–5 scale)", ge=0, le=5)
    rbc: Literal["normal", "abnormal"] = Field(..., description="Red blood cells in urine")
    pc: Literal["normal", "abnormal"] = Field(..., description="Pus cell in urine")
    pcc: Literal["present", "notpresent"] = Field(..., description="Pus cell clumps")
    ba: Literal["present", "notpresent"] = Field(..., description="Bacteria in urine")
    bgr: float = Field(..., description="Blood glucose random (mg/dL)", ge=50, le=500)
    bu: float = Field(..., description="Blood urea (mg/dL)", ge=1, le=400)
    sc: float = Field(..., description="Serum creatinine (mg/dL)", ge=0.4, le=80)
    sod: float = Field(..., description="Sodium (mEq/L)", ge=100, le=175)
    pot: float = Field(..., description="Potassium (mEq/L)", ge=2, le=50)
    hemo: float = Field(..., description="Hemoglobin (gms)", ge=3, le=20)
    pcv: float = Field(..., description="Packed cell volume (%)", ge=9, le=54)
    wc: float = Field(..., description="White blood cell count (cells/cumm)", ge=2200, le=26400)
    rc: float = Field(..., description="Red blood cell count (millions/cmm)", ge=2, le=8)
    htn: Literal["yes", "no"] = Field(..., description="Hypertension")
    dm: Literal["yes", "no"] = Field(..., description="Diabetes mellitus")
    cad: Literal["yes", "no"] = Field(..., description="Coronary artery disease")
    appet: Literal["good", "poor"] = Field(..., description="Appetite")
    pe: Literal["yes", "no"] = Field(..., description="Pedal edema")
    ane: Literal["yes", "no"] = Field(..., description="Anemia")

    model_config = ConfigDict(json_schema_extra={
        "example": {
            "age": 48, "bp": 80, "sg": 1.020, "al": 1, "su": 0,
            "rbc": "normal", "pc": "normal", "pcc": "notpresent", "ba": "notpresent",
            "bgr": 121, "bu": 36, "sc": 1.2, "sod": 137, "pot": 4.5,
            "hemo": 15.4, "pcv": 44, "wc": 7800, "rc": 5.2,
            "htn": "yes", "dm": "no", "cad": "no", "appet": "good",
            "pe": "no", "ane": "no",
        }
    })


# =============================================================================
# Schema Registry
# =============================================================================
# Maps disease names (from config) to their Pydantic input schemas.
# When a new disease is added, register its schema here.

DISEASE_SCHEMA_REGISTRY: Dict[str, Type[BaseModel]] = {
    "heart_disease": HeartDiseaseInput,
    "diabetes": DiabetesInput,
    "stroke": StrokeInput,
    "ckd": CKDInput,
}


def get_schema_for_disease(disease_name: str) -> Type[BaseModel]:
    """
    Get the Pydantic input schema for a given disease.
    
    Args:
        disease_name: The disease name as defined in its YAML config.
    
    Returns:
        The Pydantic BaseModel class for that disease.
    
    Raises:
        HTTPException 404: If no schema is registered for the disease.
    """
    if disease_name not in DISEASE_SCHEMA_REGISTRY:
        raise HTTPException(
            status_code=404,
            detail=f"No schema registered for disease '{disease_name}'. "
                   f"Available: {list(DISEASE_SCHEMA_REGISTRY.keys())}"
        )
    return DISEASE_SCHEMA_REGISTRY[disease_name]
